export default function Head() {
  return (
    <button
        className="
        text-nodeText 
          font-bold
          bg-tail_head_theme
          p-[0.5em]
          rounded-sm
          border-chainThickNess
          border-dashed
          border-nodeBorderColor
          head
          self-center
          absolute
          bottom-full
          mb-[3em]
          "
    >
      Head
      <div
        className="
                  absolute
                  border-l-chainThickNess
                  border-dashed
                  border-nodeBorderColor
                  vertical-chain
                  top-[105%]
                  left-1/2
        "
      ></div>
    </button>
  )
}
